// <auto-generated />
using ImportExcelSql.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ImportExcelSql.Migrations
{
    [DbContext(typeof(CarDbContext))]
    [Migration("20240401185924_t1")]
    partial class t1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ImportExcelSql.Models.Car", b =>
                {
                    b.Property<int>("carId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("bodyStyle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("carName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("doorNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("engineLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("horsePower")
                        .HasColumnType("int");

                    b.Property<string>("numberOfCylinders")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.HasKey("carId");

                    b.ToTable("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
